### ISSUE TITLE
Animania Suggestions Checklist

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#459]
Please read this list before opening any new suggestions

- [ ] [Suggestion] Zebras #24 

- [ ] [Suggestion] Hens 'assign' themselves to nests #38

- [ ] [FEATURE REQUEST] Thaumcraft aspects on content from this mod #52 

- [ ] [SUGGESTION] Size variances for individual animals #61

- [ ] [MINOR ISSUE] Mules unobtainable with REPLACE_VANILLA_HORSES #69 

- [ ] [SUGGESTION] Unique markings on every animal #70 

- [ ] [Suggestion] Updated Texture with more detailed shading. #79 

- [ ] Possible integration with Roost #110 

- [ ] [Suggestion] Pet food bowls for the smaller animals #114 

- [ ] [Suggestion] Age #115 

- [ ] [Suggestion] Pheasants (with special feature) #119 

- [ ] [SUGGESTION] Crafttweaker support for the aging mold #120 

- [ ] compatibility implementation with GeneticsReborn #122 

- [ ] (Suggestion) Bottle feeding baby animals! #127 

- [ ] (Suggestion) Advanced Breeding #129 

- [ ] Suggestion: show male/female indicator for baby animals #141

- [ ] [Suggestion] JourneyMap compatibility #141 

- [ ] [SUGGESTION] Replace Vanilla Horses #148 

- [ ] [Suggestion] Giraffes, Elephants and Alpacas #149 

- [ ] Suggestion - Hungry Animals compat #156 

- [ ] Chicken breeds #158 

- [ ] Draft horses doesnt have armor skin #159 

- [ ] Suggestion: Config option to have spider and cave spider attack small animals #175 

- [ ] Suggesgtion:Crabs #204 

- [ ] Suggeation:If you hurt a baby animals, its parents will attack you to defend their young #215 

- [ ] Suggestion:More intense rams dueling #217 

- [ ] Chicken eggs conversor #235 

- [ ] Honey bottle consume as much mb as a bucket #237 

- [ ] Add Hurt sound to starving animals #239 

- [ ] Check for conditions similar to vanilla animals #259 

- [ ] [Suggestion] Harvestcraft Fresh Water #256 

- [ ] Add in Ducks #276 

- [ ] Suggestion: Add Gelding (Misc suggestions: sterile charcoals and ox carting/riding) #282 

- [ ] Question/suggestions #287 

- [ ] [Request] mobs pick up tiles #339 

- [ ] Vanilla animals that should be changed by Animania #351 

- [ ] Cat and dog ideas #354

- [ ] Brown mooshroom #355 

- [ ] Request: Config option for whether Animania chicken can attack back #358

- [ ] [Suggestion] Config options for dimensional spawning blacklist/whitelist  #376 

- [ ] [Suggestion] Serene Seasons Support #377 

- [ ] [Suggestion] Stop animals from standing on troughs #384 

- [ ] suggestion: squirrels #387 

- [ ] [Suggestion] More benefits for raising animals #392 

- [ ] [Suggestion] The Ability to turn of being able to dye sheep. #401 

- [ ] [suggestion] Breeds, config options #406 

- [ ] New animal ideas #411 

- [ ] Feeding hay #427 

- [ ] [Feature] Replace vanilla animals command #430 

- [ ] Replacing existing vanilla mobs with Animania mobs? #431 

- [ ] rideable cattle, or at least rideable oxen #439

- [ ] [Feature]Liquid honey gives regeneration could be able to config #444
